'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { DollarSign, TrendingUp, Handshake, AppWindow, DatabaseZap, ShoppingBasket } from 'lucide-react';
import React from 'react';
import { useConfig } from '@/hooks/use-config';
import { Loader2 } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';

export default function InvestorOffer() {
    const { data: isaConfig, isLoading: isIsaLoading } = useConfig<any>('isaPitch');

    if (isIsaLoading) {
        return (
            <div className="flex justify-center items-center h-96">
                <Loader2 className="h-12 w-12 animate-spin text-primary" />
            </div>
        )
    }

    const isaMembershipShare = isaConfig?.membershipCommission || 30;
    const isaFinanceShare = isaConfig?.financeMallCommission || 20;
    const isaMarketplaceShare = isaConfig?.marketplaceCommission || 50;

    return (
        <div className="space-y-8 text-left text-foreground">
            <div className="text-left">
                <h1 className="text-3xl font-bold font-headline text-left">Investor Strategic Participation</h1>
                <p className="text-lg text-muted-foreground mt-2 text-left">Maximize the yield on your capital through platform-originated deal flow.</p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-8 text-left">
                <Card className="flex flex-col text-left">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-left"><DollarSign className="h-6 w-6 text-primary"/>Benefit #1: Recurring Revenue Stream</CardTitle>
                        <CardDescription className="text-left">Participate in SaaS membership growth.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4 flex-grow text-left">
                        <p className="text-sm text-muted-foreground">Direct participation in the platform's recurring income. You receive a <strong className="text-primary">{isaMembershipShare}% recurring share</strong> of all membership fees within your originated network.</p>
                    </CardContent>
                </Card>
                 <Card className="flex flex-col text-left">
                    <CardHeader className="text-left">
                        <CardTitle className="flex items-center gap-2 text-left"><TrendingUp className="h-6 w-6 text-primary"/>Benefit #2: Transactional Revenue Share</CardTitle>
                         <CardDescription className="text-left">Uncapped upside from Mall activity.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4 flex-grow text-left">
                        <p className="text-sm text-muted-foreground">Receive a <strong className="text-primary">{isaFinanceShare}% share</strong> of the platform's origination and transaction fees generated by your referred members.</p>
                    </CardContent>
                </Card>
            </div>

            <Card className="text-left">
                <CardHeader className="text-left">
                    <CardTitle className="flex items-center gap-2 text-left"><ShoppingBasket className="h-6 w-6 text-primary" />Benefit #3: Earn from Value-Added Products</CardTitle>
                    <CardDescription className="text-left">Resell specialized industrial fintech solutions.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4 text-left">
                    <p className="text-sm text-muted-foreground">Monetize high-demand reseller services within your portfolio with an immediate <strong className="text-primary">{isaMarketplaceShare}% commission split</strong>.</p>
                </CardContent>
            </Card>
        </div>
    );
}
