'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Handshake, Target, TrendingUp, DollarSign, DatabaseZap, AppWindow, Gift, ShieldCheck, BarChart, FileText } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";

const streams = [
    {
        stream: "A",
        title: "Annuity Membership Share",
        icon: TrendingUp,
        description: "Earn a fixed percentage share of all monthly and annual membership fees from your referrals. This creates a stable, scalable recurring income.",
        proposedShare: "25"
    },
    {
        stream: "B",
        title: "Mall Transactional Share",
        icon: DollarSign,
        description: "Participate in the platform's commission from every transaction in our Malls (Supplier, Buy & Sell, etc.). Upside is uncapped and tied to activity.",
        proposedShare: "10"
    },
    {
        stream: "C",
        title: "Marketplace Product Splits",
        icon: AppWindow,
        description: "Share in the revenue from third-party value-added products like specialized insurance and driver benefit schemes sold to your network.",
        proposedShare: "15"
    },
    {
        stream: "D",
        title: "Origination & Data Credits",
        icon: DatabaseZap,
        description: "Receive credits for high-quality data contributions and pre-vetted leads that result in successful funding matches through the platform.",
        proposedShare: "5"
    }
];

export default function Framework({ partner }: { partner?: any }) {
    const recipientName = partner?.firstName || 'Partner';
    const companyName = partner?.companyName || 'your business';

    return (
        <div className="space-y-8 max-w-5xl mx-auto">
            <div className="text-center">
                <h1 className="text-3xl font-bold font-headline">Partnership Framework for {companyName}</h1>
                <p className="mt-2 text-lg text-muted-foreground">A strategic commercial model designed for long-term industry alignment.</p>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-3">
                        <Target className="h-6 w-6 text-primary" />
                        Our Objective for {recipientName}
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-lg">To provide {companyName} with the tools and incentives to digitize your existing network, leveraging collective data to unlock funding, savings, and new revenue streams for everyone involved.</p>
                </CardContent>
            </Card>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                           <TrendingUp className="h-6 w-6 text-primary" />
                            Multi-Stream Engine
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-sm text-muted-foreground">The model allows {recipientName} to participate in the total economic value generated by your network across all platform divisions.</p>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                            <DatabaseZap className="h-6 w-6 text-primary" />
                            Verified Ledger
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-sm text-muted-foreground">Transactions are recorded on a verified digital ledger, creating an operational track record for {companyName} and your referrals.</p>
                    </CardContent>
                </Card>
            </div>


            <div>
                <h2 className="text-2xl font-bold text-center mb-6">Proposed Commercial Splits</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {streams.map((stream) => {
                        const Icon = stream.icon;
                        return (
                            <Card key={stream.stream}>
                                <CardHeader>
                                    <CardTitle className="flex items-start gap-3">
                                        <div className="bg-primary/10 p-2 rounded-full">
                                            <Icon className="h-6 w-6 text-primary" />
                                        </div>
                                        <div className="text-lg font-bold">
                                            Stream {stream.stream}: {stream.title}
                                        </div>
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground text-sm leading-relaxed">{stream.description}</p>
                                    <div className="flex items-center gap-3 pt-2">
                                        <Label className="font-semibold text-foreground">Proposed {recipientName}'s Share:</Label>
                                        <div className="flex items-center gap-1.5">
                                            <Input type="text" readOnly value={stream.proposedShare} className="w-16 font-bold text-lg text-center h-9" />
                                            <span className="text-lg font-bold text-primary">%</span>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        )
                    })}
                </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pt-8">
                 <Card className="bg-muted/20">
                    <CardHeader>
                        <CardTitle className="text-base flex items-center gap-2">
                            <Gift className="h-4 w-4 text-primary" />
                            Core Benefits
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="text-xs space-y-2 text-muted-foreground">
                        <p>• Lifetime Premium Membership</p>
                        <p>• Dedicated Partner Manager</p>
                        <p>• Co-branded Onboarding Landing Pages</p>
                    </CardContent>
                </Card>
                 <Card className="bg-muted/20">
                    <CardHeader>
                        <CardTitle className="text-base flex items-center gap-2">
                            <BarChart className="h-4 w-4 text-primary" />
                            Transparency
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="text-xs space-y-2 text-muted-foreground">
                        <p>• Real-time Referral Dashboard</p>
                        <p>• Automated Weekly Wallet Settlements</p>
                        <p>• Detailed Transaction Reporting</p>
                    </CardContent>
                </Card>
                 <Card className="bg-muted/20">
                    <CardHeader>
                        <CardTitle className="text-base flex items-center gap-2">
                            <FileText className="h-4 w-4 text-primary" />
                            Activation
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="text-xs leading-relaxed text-muted-foreground">
                        <p>Upon acceptance of these terms, we will provision {companyName}'s unique tracking IDs and generate the formal Strategic Partnership Agreement.</p>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
