
'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Loader2, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { useCollection, useFirestore, useMemoFirebase } from '@/firebase';
import { collectionGroup, query } from 'firebase/firestore';
import { Badge } from '@/components/ui/badge';


const statusColors: { [key: string]: 'default' | 'secondary' | 'destructive' | 'outline' } = {
  pending: 'secondary',
  under_review: 'outline',
  matched: 'default',
  rejected: 'destructive',
  funded: 'default',
  quote: 'outline',
};

const formatPrice = (price: number) => {
    if (typeof price !== 'number') return 'N/A';
    return new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR' }).format(price);
};

const formatDate = (isoString: string | undefined) => {
    if (!isoString) return 'N/A';
    try {
        return new Date(isoString).toLocaleDateString('en-ZA', { month: 'short', day: 'numeric', year: 'numeric' });
    } catch (e) {
        return 'Invalid Date';
    }
};

export default function FundingDivisionContent() {
    const firestore = useFirestore();

    const quotesQuery = useMemoFirebase(() => firestore ? query(collectionGroup(firestore, 'quotes')) : null, [firestore]);
    const enquiriesQuery = useMemoFirebase(() => firestore ? query(collectionGroup(firestore, 'enquiries')) : null, [firestore]);
    
    const { data: quotes, isLoading: isLoadingQuotes, error: quotesError } = useCollection(quotesQuery);
    const { data: enquiries, isLoading: isLoadingEnquiries, error: enquiriesError } = useCollection(enquiriesQuery);

    const isLoading = isLoadingQuotes || isLoadingEnquiries;
    const error = quotesError || enquiriesError;

    const applications = useMemo(() => {
        if (!quotes && !enquiries) return [];
        const combined = [
            ...(quotes || []).map((q: any) => ({ ...q, recordType: 'Quote' })),
            ...(enquiries || []).map((e: any) => ({ ...e, recordType: 'Enquiry' })),
        ];
        return combined.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    }, [quotes, enquiries]);

    const stats = useMemo(() => {
        if (!applications) return { applications: 0, totalRequested: 0, totalFunded: 0 };
        const totalFunded = applications.filter((app: any) => app.status === 'funded').reduce((sum: number, app: any) => sum + (app.amountRequested || 0), 0);
        const totalRequested = applications.reduce((sum: number, app: any) => sum + (app.amountRequested || 0), 0);
        return {
            applications: applications.length,
            totalRequested,
            totalFunded,
        };
    }, [applications]);


    if (isLoading) {
        return <div className="flex justify-center items-center py-20"><Loader2 className="h-12 w-12 animate-spin text-primary" /></div>;
    }
    if (error) {
        return <div className="text-destructive-foreground bg-destructive/90 p-4 rounded-md"><h4 className="font-semibold">Error</h4><p>{error.message}</p></div>;
    }

    return (
        <div className="space-y-8">
            <h1 className="text-2xl font-bold">Funding Division Dashboard</h1>
            <div className="grid gap-4 md:grid-cols-3">
                <Card><CardHeader><CardTitle>Total Applications</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{stats.applications}</div></CardContent></Card>
                <Card><CardHeader><CardTitle>Total Value Requested</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{formatPrice(stats.totalRequested)}</div></CardContent></Card>
                <Card><CardHeader><CardTitle>Total Value Funded</CardTitle></CardHeader><CardContent><div className="text-2xl font-bold">{formatPrice(stats.totalFunded)}</div></CardContent></Card>
            </div>
             <Card>
                <CardHeader>
                    <CardTitle>All Funding Records (Quotes & Enquiries)</CardTitle>
                    <CardDescription>A list of all quotes and formal enquiries generated by members across the platform.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="overflow-x-auto">
                        <Table>
                            <TableHeader><TableRow><TableCell>Date</TableCell><TableCell>Member</TableCell><TableCell>Record Type</TableCell><TableCell>Funding Type</TableCell><TableCell>Amount</TableCell><TableCell>Status</TableCell><TableCell>Action</TableCell></TableRow></TableHeader>
                            <TableBody>
                                {applications.length > 0 ? applications.map(app => (
                                    <TableRow key={`${app.recordType}-${app.id}`}>
                                        <TableCell className="text-xs">{formatDate(app.createdAt)}</TableCell>
                                        <TableCell className="font-mono text-xs max-w-[150px] truncate">
                                            <Link href={`/backend?view=wallet&memberId=${app.companyId}`} className="hover:underline text-primary">{app.companyId}</Link>
                                        </TableCell>
                                        <TableCell>
                                            <Badge variant={app.recordType === 'Quote' ? 'outline' : 'default'} className="capitalize">
                                                {app.recordType}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="capitalize">{app.fundingType?.replace(/_/g, ' ')}</TableCell>
                                        <TableCell>{formatPrice(app.amountRequested)}</TableCell>
                                        <TableCell><Badge variant={statusColors[app.status] || 'secondary'} className="capitalize">{app.status?.replace(/_/g, ' ')}</Badge></TableCell>
                                        <TableCell>
                                            <Button asChild variant="outline" size="sm">
                                                <Link href={`/backend?view=wallet&memberId=${app.companyId}`}>View Member</Link>
                                            </Button>
                                        </TableCell>
                                    </TableRow>
                                )) : (
                                    <TableRow>
                                        <TableCell colSpan={7} className="text-center h-24 text-muted-foreground">No funding records found.</TableCell>
                                    </TableRow>
                                )}
                            </TableBody>
                        </Table>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
