'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useUser } from '@/firebase';
import { ArrowRight, Heart } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { placeholderImages } from '@/lib/placeholder-images.json';

const loyaltyImage = placeholderImages.find(p => p.id === 'funding-division');

export default function LoyaltyPlanPage() {
    const { user } = useUser();
    const ctaLink = user ? '/account' : '/signin';
    
    return (
        <div className="container mx-auto px-4 py-16">
            <div className="max-w-4xl mx-auto">
                <Card className="overflow-hidden">
                     {loyaltyImage && (
                        <div className="relative w-full h-56 bg-card">
                            <Image
                                src={loyaltyImage.imageUrl}
                                alt="Loyalty Plan"
                                fill
                                className="object-cover"
                                data-ai-hint={loyaltyImage.imageHint}
                            />
                             <div className="absolute inset-0 bg-black/50" />
                        </div>
                     )}
                    <CardHeader className="relative border-b">
                         <div className="flex items-center gap-4">
                            <Heart className="h-12 w-12 text-primary" />
                            <div>
                                <h1 className="text-3xl md:text-4xl font-bold font-headline">Loyalty Plan</h1>
                                <p className="text-lg text-primary font-semibold">R 50/month</p>
                            </div>
                        </div>
                    </CardHeader>
                    <CardContent className="p-6 space-y-6">
                        <p className="text-lg text-muted-foreground">
                            The Loyalty Plan is your path to increasing your share of the rewards generated by the collective buying power of the TransConnect community. The more we grow together, the more you save.
                        </p>
                        
                        <div>
                            <h3 className="text-xl font-semibold mb-3">The Power of Community:</h3>
                            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                                <li><span className="font-semibold text-foreground">Group Discounts:</span> By negotiating with suppliers on behalf of all our members, we secure significant discounts that no single transporter could achieve alone.</li>
                                <li><span className="font-semibold text-foreground">Shared Savings:</span> A portion of these negotiated savings is passed back to our members. The Loyalty Plan gives you access to these shared benefits.</li>
                                <li><span className="font-semibold text-foreground">Tiered Rewards:</span> As you move up the loyalty tiers, you claim a larger percentage of the available discounts, maximizing your savings. Use the calculator on the Connect page to see your potential.</li>
                            </ul>
                        </div>
                        
                        <p className="text-lg text-muted-foreground">
                          This plan is perfect for any member who wants to directly benefit from the scale of the TransConnect network. Your loyalty is rewarded with real, measurable savings on the products and services you use every day.
                        </p>
                        
                        <div className="text-center pt-6">
                             <Button asChild size="lg">
                                <Link href={ctaLink}>
                                    Activate Loyalty Plan <ArrowRight className="ml-2 h-4 w-4" />
                                </Link>
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
