
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Handshake, Target, TrendingUp, DollarSign, DatabaseZap, AppWindow, Gift, ShieldCheck, BarChart, FileText } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";

const streams = [
    {
        stream: "A",
        title: "Recurring Annuity",
        icon: TrendingUp,
        description: "Earn a fixed percentage share of all monthly and annual membership fees. This creates a stable, predictable recurring income that scales with every sign-up.",
        proposedShare: "25"
    },
    {
        stream: "B",
        title: "Transactional Volume",
        icon: DollarSign,
        description: "Participate in the platform's commission from every transaction in our Malls (Supplier, Buy & Sell, etc.). Upside is uncapped and tied to network activity.",
        proposedShare: "10"
    },
    {
        stream: "C",
        title: "Marketplace Splits",
        icon: AppWindow,
        description: "Share in the revenue from third-party value-added products like specialized insurance, fuel programs, and driver benefit schemes.",
        proposedShare: "15"
    },
    {
        stream: "D",
        title: "Funding Origination",
        icon: DatabaseZap,
        description: "Reward for data-quality and vetting. Earn a credit on successfully funded deals matched through the Funding Division origination engine.",
        proposedShare: "5"
    }
];

export default function PitchPartnerFramework() {
    return (
        <div className="space-y-8 max-w-5xl mx-auto">
            <div className="text-center">
                <h1 className="text-3xl font-bold font-headline">Formal Partnership Framework</h1>
                <p className="mt-2 text-lg text-muted-foreground">A strategic commercial model designed for industry alliances and high-growth partners.</p>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-3">
                        <Target className="h-6 w-6 text-primary" />
                        Core Objective
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-lg">To digitize the logistics community and leverage collective data to unlock funding and savings.</p>
                </CardContent>
            </Card>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                           <TrendingUp className="h-6 w-6 text-primary" />
                            Commercial Engine
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>A multi-stream revenue model encompassing memberships, mall transactions, and marketplace products.</p>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                            <DatabaseZap className="h-6 w-6 text-primary" />
                            Data Sovereignty
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>All transactions recorded on a verified digital ledger, creating an operational track record for funding.</p>
                    </CardContent>
                </Card>
            </div>


            <div>
                <h2 className="text-2xl font-bold text-center mb-6">The Multi-Stream Commercial Model</h2>
                <p className="text-center text-muted-foreground mb-8">Partners participate in the total economic value generated by their network.</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {streams.map((stream) => {
                        const Icon = stream.icon;
                        return (
                            <Card key={stream.stream}>
                                <CardHeader>
                                    <CardTitle className="flex items-start gap-3">
                                        <div className="bg-primary/10 p-2 rounded-full">
                                            <Icon className="h-6 w-6 text-primary" />
                                        </div>
                                        <div>
                                            Stream {stream.stream}: {stream.title}
                                        </div>
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <p className="text-muted-foreground text-sm">{stream.description}</p>
                                    <div className="space-y-2">
                                        <Label>Proposed Share:</Label>
                                        <div className="flex items-center gap-2">
                                            <Input type="text" readOnly value={stream.proposedShare} className="w-20 font-bold text-lg text-center" />
                                            <span className="text-lg font-bold">%</span>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        )
                    })}
                </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                            <Gift className="h-6 w-6 text-primary" />
                            Foundations: Partner Benefits
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-2">
                        <p>&#x2022; Free Lifetime Premium Membership</p>
                        <p>&#x2022; Exclusive Partner-only Support Channel</p>
                        <p>&#x2022; Early Access to New Tech Features</p>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                            <BarChart className="h-6 w-6 text-primary" />
                            Management & Transparency
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-2">
                        <p>&#x2022; Real-time Referral Tracking</p>
                        <p>&#x2022; Automated Weekly Wallet Payouts</p>
                    </CardContent>
                </Card>
                 <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-3">
                            <FileText className="h-6 w-6 text-primary" />
                            Path to Formalization
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p>This framework serves as the basis for a formal Strategic Partnership Agreement. Upon acceptance of the core commercial terms, we will proceed to activate your Partner Dashboard and provide unique referral onboarding links.</p>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
