'use client';

import { Card, CardContent, CardDescription, CardHeader, CardFooter, CardTitle } from '@/components/ui/card';
import { UserCheck, ShieldCheck } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import React from 'react';
import { useSearchParams } from 'next/navigation';
import { useUser } from '@/firebase';

const EmailTemplate = ({ subject, content, partner, referralLink }: { subject: string, content: string, partner: any, referralLink: string }) => {
    const personalizedContent = React.useMemo(() => {
        let text = content;
        const name = partner?.firstName || '[Supplier Name]';
        const company = partner?.companyName || '[Your Company]';
        
        text = text.replace(/\[Supplier Name\]/g, name);
        text = text.replace(/\[Name\]/g, name);
        text = text.replace(/\[Lead Name\]/g, name);
        text = text.replace(/\[Your Company\]/g, company);
        text = text.replace(/\[Referral Link\]/g, referralLink);
        text = text.replace(/\[Sign-up Link\]/g, referralLink);
        text = text.replace(/\[Opt-in Link\]/g, `${window.location.origin}/opt-in/${partner?.id || 'TEST'}`);

        return text;
    }, [content, partner, referralLink]);

    return (
        <Card className="border-none shadow-none bg-transparent">
            <CardHeader className="px-0">
                <div className="flex items-center justify-between">
                    <div>
                        <CardTitle className="text-lg">Email Subject</CardTitle>
                        <CardDescription className="font-medium text-foreground select-all">{subject}</CardDescription>
                    </div>
                    {partner && (
                         <div className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1.5 border border-green-200">
                            <UserCheck className="h-3.5 w-3.5" /> Personalized for {partner.firstName}
                        </div>
                    )}
                </div>
            </CardHeader>
            <CardContent className="px-0">
                <div className="p-6 bg-white border rounded-md whitespace-pre-wrap font-sans text-sm shadow-inner min-h-[300px]">
                    {personalizedContent.trim()}
                </div>
            </CardContent>
            {partner && (
                <CardFooter className="px-0 pt-4 border-t mt-4 text-xs text-muted-foreground italic text-center">
                    Copy HTML via the main toolbar to embed tracking and log this interaction.
                </CardFooter>
            )}
        </Card>
    );
};

const getTemplates = (supplierType: string) => ({
    handshake: {
        subject: `The Digital Handshake: [Your Company] Supplier Profile`,
        content: `
Hi [Supplier Name],

I'm reaching out from Logistics Flow. We're currently expanding our network of ${supplierType} vendors, and we'd love to have [Your Company] listed.

Before we can send you quote requests or invite you to create your digital storefront, we require a "Digital Handshake" to confirm your interest and ensure we are POPI-compliant.

Please take 30 seconds to establish the connection here:
[Opt-in Link]

Establishing this handshake allows you to:
- Reach a targeted community of fleet owners.
- Receive direct RFQs for ${supplierType}.
- Enable embedded finance for your customers.

Best regards,

The Logistics Flow Team
        `
    },
    intro: {
        subject: `A New Sales Channel for Your ${supplierType} Business`,
        content: `
Hi [Supplier Name],

I'm reaching out with an opportunity to list your business on Logistics Flow, a digital ecosystem for the transport industry, completely free of charge.

The central focus of our platform is to provide you with a digital twin of your business. This isn't just a simple storefront; it's a comprehensive digital branch exposed to a community of fleet owners actively looking for your products.

Our unique sign-up link for [Your Company] is ready: [Sign-up Link]

Best regards,

[Your Name]
        `
    },
    revenue: {
        subject: "Turn Your Client Base into a Recurring Revenue Engine",
        content: `
Dear [Supplier Name],

Beyond direct sales through our platform, Logistics Flow offers a unique partnership opportunity to generate a new, recurring revenue stream from your existing client base at [Your Company].

How it works:
- When your clients join Logistics Flow through your link to manage their own operations, you earn a commission.
- This isn't a one-time fee. You earn a share of the revenue generated by their activity across our entire ecosystem.

Review your partner benefits here: [Sign-up Link]

Best regards,

[Your Name]
        `
    }
});

const tabs = [
    { value: "handshake", label: "0. Digital Handshake", icon: ShieldCheck },
    { value: "intro", label: "1. Digital Branch" },
    { value: "revenue", label: "2. Revenue Model" },
];


export default function SupplierEmails({ partner }: { partner?: any }) {
    const { user } = useUser();
    const searchParams = useSearchParams();
    const supplierType = searchParams.get('type') || 'General';
    const templates = getTemplates(supplierType);
    const baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://studio--ecosystem-hub.us-central1.hosted.app';

    const referralLink = React.useMemo(() => {
        if (!partner) return `${baseUrl}/join`;
        return `${baseUrl}/join?ref=${partner.id}&role=vendor&type=${encodeURIComponent(supplierType)}`;
    }, [partner, baseUrl, supplierType]);

    return (
        <div className="space-y-6">
            <Tabs defaultValue="handshake" className="w-full">
                <TabsList className="h-auto flex-wrap justify-start bg-muted/30">
                   {tabs.map(tab => {
                       const Icon = tab.icon;
                       return (
                           <TabsTrigger key={tab.value} value={tab.value} className="text-xs gap-2">
                               {Icon && <Icon className="h-3 w-3" />}
                               {tab.label}
                           </TabsTrigger>
                       );
                   })}
                </TabsList>
                {Object.entries(templates).map(([key, t]) => (
                    <TabsContent key={key} value={key} className="mt-6">
                        <EmailTemplate 
                            subject={t.subject} 
                            content={t.content.replace(/\[Your Name\]/g, user?.displayName || 'TransConnect Team')} 
                            partner={partner} 
                            referralLink={referralLink}
                        />
                    </TabsContent>
                ))}
            </Tabs>
        </div>
    );
}
