'use client';

import React, { useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { getClientSideAuthToken } from '@/firebase';
import { Loader2, Upload, FileText, Download, FileJson } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

interface BulkImportDialogProps {
    type: string;
    onComplete: () => void;
    children: React.ReactNode;
}

export function BulkImportDialog({ type, onComplete, children }: BulkImportDialogProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [isUploading, setIsUploading] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const { toast } = useToast();

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
        }
    };

    const handleImport = async () => {
        if (!file) return;

        setIsUploading(true);
        try {
            const token = await getClientSideAuthToken();
            if (!token) throw new Error("Authentication failed.");

            const text = await file.text();
            let partners: any[] = [];

            if (file.name.toLowerCase().endsWith('.json')) {
                // Support for the specific JSON format generated by Google AI
                try {
                    const rawData = JSON.parse(text);
                    const dataArray = Array.isArray(rawData) ? rawData : [rawData];
                    
                    partners = dataArray.map((item: any) => ({
                        companyName: item.company_name || item.companyName || item.company || 'Unknown Company',
                        contactPerson: item.contact_person || item.contactPerson || item.contact || 'N/A',
                        email: item.email_address || item.email || '',
                        phone: item.telephone_number || item.phone || item.cell || '',
                        website: item.website || item.url || '',
                        address: item.physical_address || item.address || '',
                    }));
                } catch (e) {
                    throw new Error("Invalid JSON file. Please ensure it is a valid array of objects.");
                }
            } else {
                // CSV Parsing Logic
                const cleanText = text.startsWith('\ufeff') ? text.slice(1) : text;
                const rows = cleanText.split(/\r?\n/).filter(row => row.trim().length > 0);
                
                if (rows.length < 2) throw new Error("CSV file is empty or missing data rows.");

                let delimiter = ',';
                if (rows[0].includes(';')) delimiter = ';';
                if (rows[0].includes('\t')) delimiter = '\t';

                const headers = rows[0].split(delimiter).map(h => h.trim().toLowerCase().replace(/["']/g, ''));
                const dataRows = rows.slice(1);

                partners = dataRows.map((row) => {
                    const values = row.split(delimiter).map(v => v.trim().replace(/^["']|["']$/g, ''));
                    const p: any = {};
                    
                    headers.forEach((header, index) => {
                        const val = values[index];
                        if (!val) return; 

                        if (header === 'name' || header === 'contact' || header === 'contact name' || header === 'contact_person') {
                            p.contactPerson = val;
                            const nameParts = val.split(' ');
                            p.firstName = nameParts[0] || 'Member';
                            p.lastName = nameParts.slice(1).join(' ') || 'Candidate';
                        } else if (header.includes('email')) {
                            p.email = val;
                        } else if (header.includes('phone') || header.includes('cell') || header.includes('mobile') || header === 'telephone_number') {
                            p.phone = val;
                        } else if (header.includes('company') || header.includes('business') || header === 'company_name') {
                            p.companyName = val;
                        } else if (header.includes('address')) {
                            p.address = val;
                        } else if (header.includes('website') || header.includes('url')) {
                            p.website = val;
                        }
                    });

                    if (!p.firstName) p.firstName = p.contactPerson?.split(' ')[0] || 'Member';
                    if (!p.lastName) p.lastName = p.contactPerson?.split(' ').slice(1).join(' ') || 'Candidate';
                    if (!p.companyName) p.companyName = p.contactPerson || 'Unknown Company';

                    return p;
                });
            }

            const validPartners = partners.filter(p => p.companyName || p.email);

            if (validPartners.length === 0) {
                throw new Error(`No valid records found. Ensure your file has a 'Company' or 'Name' header.`);
            }

            const response = await fetch('/api/admin', {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    action: 'bulkSavePartners',
                    payload: { partners: validPartners, type }
                }),
            });

            const result = await response.json();
            if (!response.ok) throw new Error(result.error || "Import failed.");

            toast({ title: "Import Successful", description: `Added ${validPartners.length} ${type}s to the database.` });
            setIsOpen(false);
            onComplete();
        } catch (e: any) {
            toast({ variant: 'destructive', title: "Import Failed", description: e.message });
        } finally {
            setIsUploading(false);
            setFile(null);
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild>{children}</DialogTrigger>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>Bulk Import {type.charAt(0).toUpperCase() + type.slice(1)}s</DialogTitle>
                    <DialogDescription>Upload a CSV or JSON file. I've updated the logic to recognize the Google AI format you used.</DialogDescription>
                </DialogHeader>
                <div className="space-y-4 py-4">
                    <Alert className="bg-primary/5 border-primary/20">
                        <FileJson className="h-4 w-4 text-primary" />
                        <AlertTitle className="text-primary font-bold">New: JSON Support</AlertTitle>
                        <AlertDescription className="text-xs">
                            You can now drop in the JSON batches provided by your AI chat. I'll automatically map the fields correctly.
                        </AlertDescription>
                    </Alert>
                    <div className="space-y-2">
                        <Label htmlFor="import-file">Select CSV or JSON Batch File</Label>
                        <Input id="import-file" type="file" accept=".csv,.json" onChange={handleFileChange} disabled={isUploading} />
                    </div>
                </div>
                <DialogFooter className="sm:justify-between">
                    <Button variant="ghost" onClick={() => setIsOpen(false)} disabled={isUploading}>Cancel</Button>
                    <Button onClick={handleImport} disabled={!file || isUploading}>
                        {isUploading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Upload className="mr-2 h-4 w-4" />}
                        Start Batch Import
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
